# Generated by Django 4.2.21 on 2025-12-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bijak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_code",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="کد رهگیری"
                    ),
                ),
                (
                    "issuance_date",
                    django_jalali.db.models.jDateField(
                        verbose_name="تاریخ صدور بارنامه"
                    ),
                ),
                (
                    "issuance_time",
                    django_jalali.db.models.jDateTimeField(
                        verbose_name="ساعت صدور بارنامه"
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="ارزش محموله")),
                ("insurance", models.CharField(max_length=100, verbose_name="حق بیمه")),
                (
                    "loading_fee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="هزینه بارگیری",
                    ),
                ),
                (
                    "unloading_fee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="هزینه تخلیه",
                    ),
                ),
                (
                    "scale_fee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="هزینه باسکول",
                    ),
                ),
                (
                    "freight",
                    models.CharField(max_length=100, verbose_name="مبلغ کرایه"),
                ),
                (
                    "total_fare",
                    models.CharField(
                        max_length=100, verbose_name="کل کرایه پرداختی در مقصد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("issued", "صادر شده"),
                            ("waiting_approval", "در انتظار تأیید مدیر"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("sent", "ارسال شده"),
                            ("delivered", "تحویل شده"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Fare change", "تغییر کرایه"),
                            ("informal", "سوری"),
                            ("reprint", "چاپ مجدد"),
                            ("driver_request", "به درخواست راننده"),
                        ],
                        max_length=50,
                    ),
                ),
                ("custom_caption", models.TextField(blank=True, null=True)),
                ("final_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="نام و نام خانوادگی راننده"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد ملی راننده"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام پدر"
                    ),
                ),
                (
                    "birth_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ تولد"
                    ),
                ),
                (
                    "residence",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شهر محل سکونت",
                    ),
                ),
                (
                    "certificate",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره گواهینامه"
                    ),
                ),
                (
                    "certificate_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ صدور گواهینامه"
                    ),
                ),
                (
                    "driver_smart_card",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="هوشمند راننده",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="شماره تلفن راننده"),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="شماره تلفن دوم",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="آدرس محل سکونت"
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="شماره بیمه نامه شخص ثالث",
                    ),
                ),
                (
                    "insurance_policy_expiry",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="تاریخ انقضاء بیمه نامه شخص ثالث",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=50, verbose_name="نوع وسیله")),
                (
                    "license_plate_two_digit",
                    models.CharField(max_length=2, verbose_name="دو رقم پلاک"),
                ),
                (
                    "license_plate_alphabet",
                    models.CharField(max_length=1, verbose_name="الفبای پلاک"),
                ),
                (
                    "license_plate_three_digit",
                    models.CharField(max_length=3, verbose_name="سه رقم پلاک"),
                ),
                (
                    "license_plate_series",
                    models.CharField(max_length=2, verbose_name="سری پلاک"),
                ),
                (
                    "vehicle_smart_card",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="هوشمند ناوگان",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issuance.driver",
                        verbose_name="انتخاب راننده",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="نام و نام خانوادگی فرستنده"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="شناسه یا کد ملی",
                    ),
                ),
                (
                    "postal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد پستی"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="تلفن"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "phone2",
                    models.TextField(blank=True, null=True, verbose_name="تلفن دوم"),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="نام محموله")),
                (
                    "weight",
                    models.CharField(
                        max_length=5, verbose_name="وزن(کیلوگرم)/حجم(لیتر)"
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="نوع بسته بندی",
                    ),
                ),
                (
                    "number_of_packaging",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        verbose_name="تعداد بسته بندی",
                    ),
                ),
                (
                    "origin",
                    models.CharField(max_length=50, verbose_name="مبدا بارگیری"),
                ),
                (
                    "destination",
                    models.CharField(max_length=50, verbose_name="مقصد تخلیه"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Caption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "updated_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BijakApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("sent_for_approval", "ارسال برای تایید"),
                            ("approved", "تایید شد"),
                            ("rejected", "رد شد"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bijak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="issuance.bijak",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه تایید بیجک",
                "verbose_name_plural": "تاریخچه تایید بیجک ها",
            },
        ),
        migrations.AddField(
            model_name="bijak",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_bijaks",
                to="issuance.cargo",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_bijaks",
                to="issuance.driver",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="insurance_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_bijaks",
                to="issuance.insurance",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_bijaks",
                to="issuance.customer",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="selected_caption",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caption_bijaks",
                to="issuance.caption",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_bijaks",
                to="issuance.customer",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_bijaks",
                to="issuance.vehicle",
            ),
        ),
    ]
