# Generated by Django 4.2.21 on 2025-11-03 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="توضیحات")),
            ],
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام محموله")),
                (
                    "weight",
                    models.CharField(
                        max_length=5, verbose_name="وزن(کیلوگرم)/حجم(لیتر)"
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="نوع بسته بندی"
                    ),
                ),
                (
                    "number_of_packaging",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="تعداد بسته بندی"
                    ),
                ),
                (
                    "origin",
                    models.CharField(max_length=50, verbose_name="مبدا بارگیری"),
                ),
                (
                    "destination",
                    models.CharField(max_length=50, verbose_name="مقصد تخلیه"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="نام و نام خانوادگی فرستنده"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="شناسه یا کد ملی",
                    ),
                ),
                (
                    "postal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد پستی"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="تلفن"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "phone2",
                    models.TextField(blank=True, null=True, verbose_name="تلفن دوم"),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="نام و نام خانوادگی راننده"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد ملی راننده"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(max_length=50, verbose_name="نام پدر"),
                ),
                (
                    "birth_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ تولد"),
                ),
                (
                    "residence",
                    models.CharField(max_length=100, verbose_name="شهر محل سکونت"),
                ),
                (
                    "certificate",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره گواهینامه"
                    ),
                ),
                (
                    "certificate_date",
                    django_jalali.db.models.jDateField(
                        verbose_name="تاریخ صدور گواهینامه"
                    ),
                ),
                (
                    "driver_smart_card",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="هوشمند راننده",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="شماره تلفن راننده"),
                ),
                (
                    "phone2",
                    models.CharField(max_length=15, verbose_name="شماره تلفن دوم"),
                ),
                ("address", models.TextField(verbose_name="آدرس محل سکونت")),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10, verbose_name="نوع وسیله")),
                (
                    "license_plate_two_digit",
                    models.CharField(max_length=2, verbose_name="دو رقم پلاک"),
                ),
                (
                    "license_plate_alphabet",
                    models.CharField(max_length=1, verbose_name="الفبای پلاک"),
                ),
                (
                    "license_plate_three_digit",
                    models.CharField(max_length=3, verbose_name="سه رقم پلاک"),
                ),
                (
                    "license_plate_series",
                    models.CharField(max_length=2, verbose_name="سری پلاک"),
                ),
                (
                    "vehicle_smart_card",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="هوشمند ناوگان",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issuance.driver",
                        verbose_name="انتخاب راننده",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bijak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="کد رهگیری"
                    ),
                ),
                (
                    "issuance_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ صدور"),
                ),
                ("value", models.CharField(max_length=100, verbose_name="ارزش محموله")),
                (
                    "insurance",
                    models.CharField(max_length=100, verbose_name="مبلغ بیمه"),
                ),
                (
                    "loading_fee",
                    models.CharField(max_length=100, verbose_name="هزینه خدمات"),
                ),
                (
                    "freight",
                    models.CharField(max_length=100, verbose_name="مبلغ کرایه"),
                ),
                (
                    "total_fare",
                    models.CharField(
                        max_length=100, verbose_name="کل کرایه پرداختی در مقصد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("issued", "صادر شده"),
                            ("sent", "ارسال شده"),
                        ],
                        max_length=30,
                    ),
                ),
                ("custom_caption", models.TextField(blank=True, null=True)),
                ("final_description", models.TextField(blank=True, null=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargoـbijaks",
                        to="issuance.cargo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driverـbijaks",
                        to="issuance.driver",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_bijaks",
                        to="issuance.customer",
                    ),
                ),
                (
                    "selected_caption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caption_bijaks",
                        to="issuance.caption",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_bijaks",
                        to="issuance.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicleـbijaks",
                        to="issuance.vehicle",
                    ),
                ),
            ],
        ),
    ]
