# Generated by Django 4.2.21 on 2025-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه یا کد ملی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
    ]
