# Generated by Django 4.2.21 on 2025-09-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issuance", "0002_alter_customer_national_id_alter_customer_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bijak",
            name="caption",
        ),
        migrations.AddField(
            model_name="bijak",
            name="captions",
            field=models.ManyToManyField(
                blank=True,
                related_name="bijaks",
                to="issuance.caption",
                verbose_name="توضیحات آماده",
            ),
        ),
        migrations.AddField(
            model_name="bijak",
            name="custom_caption",
            field=models.TextField(blank=True, null=True, verbose_name="توضیح دستی"),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargoـbijaks",
                to="issuance.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driverـbijaks",
                to="issuance.driver",
            ),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="freight",
            field=models.CharField(max_length=100, verbose_name="مبلغ کرایه"),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="loading_fee",
            field=models.CharField(max_length=100, verbose_name="هزینه خدمات"),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_bijaks",
                to="issuance.customer",
            ),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_bijaks",
                to="issuance.customer",
            ),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="total_fare",
            field=models.CharField(
                max_length=100, verbose_name="کل کرایه پرداختی در مقصد"
            ),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="tracking_code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="کد رهگیری"
            ),
        ),
        migrations.AlterField(
            model_name="bijak",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicleـbijaks",
                to="issuance.vehicle",
            ),
        ),
    ]
