# Generated by Django 4.2.21 on 2025-05-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('brith_place', models.TextField()),
                ('father_name', models.TextField()),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('phone2', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('certificate', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('postal', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('postal', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('license_plate_three_digit', models.CharField(max_length=3)),
                ('license_plate_alphabet', models.TextField(max_length=1)),
                ('license_plate_two_digit', models.CharField(max_length=2)),
                ('license_plate_series', models.CharField(max_length=2)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BijakForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('value', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.driver')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.sender')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.vehicle')),
            ],
        ),
    ]
