# Generated by Django 4.2.21 on 2025-06-08 22:10

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محموله')),
                ('weight', models.IntegerField(max_length=5, verbose_name='وزن(کیلوگرم)/حجم(لیتر)')),
                ('package_type', models.CharField(max_length=10, verbose_name='نوع بسته بندی')),
                ('number_of_packaging', models.IntegerField(max_length=3, verbose_name='تعداد بسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی راننده')),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='کد ملی راننده')),
                ('brith_place', models.CharField(max_length=10, verbose_name='محل تولد')),
                ('father_name', models.CharField(max_length=10, verbose_name='نام پدر')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن راننده')),
                ('phone2', models.CharField(max_length=11, verbose_name='شماره تلفن دوم')),
                ('address', models.TextField(verbose_name='آدرس محل سکونت')),
                ('certificate', models.CharField(max_length=50, unique=True, verbose_name='شماره گواهینامه')),
                ('certificate_date', models.DateField(verbose_name='تاریخ صدور گواهینامه')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی گیرنده')),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='شناسه یا کد ملی')),
                ('postal', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی فرستنده')),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='شناسه یا کد ملی')),
                ('postal', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='نوع وسیله')),
                ('license_plate_three_digit', models.IntegerField(max_length=3, verbose_name='سه رقم پلاک')),
                ('license_plate_alphabet', models.CharField(max_length=1, verbose_name='الفبای پلاک')),
                ('license_plate_two_digit', models.IntegerField(max_length=2, verbose_name='دو رقم پلاک')),
                ('license_plate_series', models.CharField(max_length=2, verbose_name='سری پلاک')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BijakForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=10, verbose_name='کد رهگیری')),
                ('issuance_date', django_jalali.db.models.jDateField(verbose_name='تاریخ صدور')),
                ('value', models.CharField(max_length=100, verbose_name='ارزش محموله')),
                ('origin', models.CharField(max_length=50, verbose_name='مبدا بارگیری')),
                ('destination', models.CharField(max_length=50, verbose_name='مقصد تخلیه')),
                ('insurance', models.CharField(max_length=100, verbose_name='مبلغ بیمه')),
                ('loading_fee', models.CharField(max_length=10, verbose_name='هزینه خدمات')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.driver')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.sender')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.vehicle')),
            ],
        ),
    ]
