# Generated by Django 4.2.21 on 2025-06-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bijak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijakform',
            name='loading_fee',
            field=models.CharField(blank=True, max_length=10, verbose_name='هزینه خدمات'),
        ),
        migrations.AlterField(
            model_name='bijakform',
            name='origin',
            field=models.CharField(blank=True, max_length=50, verbose_name='مبدا بارگیری'),
        ),
        migrations.AlterField(
            model_name='bijakform',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='ارزش محموله'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='number_of_packaging',
            field=models.IntegerField(blank=True, max_length=3, verbose_name='تعداد بسته بندی'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='package_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='نوع بسته بندی'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(blank=True, max_length=5, verbose_name='وزن(کیلوگرم)/حجم(لیتر)'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='شناسه یا کد ملی'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='شناسه یا کد ملی'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijak.driver', verbose_name='انتخاب راننده'),
        ),
    ]
