# Generated by Django 4.2.21 on 2025-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bijak', '0002_alter_bijakform_loading_fee_alter_bijakform_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه یا کد ملی'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
    ]
